### ISSUE TITLE
Cadastrar informações das disciplinas

### ISSUE THREAD

**Issue by magsilva** [humbbetao/projectUtfpr#11]
Cadastrar informações das disciplinas conforme projeto do curso e o site http://www.utfpr.edu.br/campomourao/cursos/bacharelados/Ofertados-neste-Campus/ciencia-da-computacao/ementario-e-carga-horaria-das-disciplinas

**Comment by humbbetao** [comment]
PRÉ-REQUISITO e EQUIVALÊNCIA, OBJETIVOS eu cadastro na matriz ou na disciplina?

**Comment by magsilva** [comment]
Na disciplina.
