### ISSUE TITLE
Criar casos de teste para o parsing dos dados de projeto do Lattes

### ISSUE THREAD

**Issue by magsilva** [humbbetao/projectUtfpr#12]
Criar casos de teste para o parsing dos dados de projeto do Lattes. As diretivas seguem aquelas do 'unittest: https://docs.python.org/3/library/unittest.html#module-unittest

Basicamente, é criar um caso de teste que executa a importação dos dados (leitura do XML) e compara os dados item do modelo criado com os dados esperados da importação dos dados. Para tanto, você pode criar vários arquivos XML (mínimos, apenas com os dados necessários para cada caso de teste). Assim, ficaria um arquivo para cada caso de teste (cada caso de teste é um método distinto, pode ter mais de um método/caso de teste na mesma classe).

Subsídios para teste de unidade no Django:
- https://docs.djangoproject.com/en/1.9/topics/testing/
- https://docs.djangoproject.com/en/1.9/topics/testing/tools/
- https://docs.djangoproject.com/en/1.9/topics/testing/advanced/8

**Comment by humbbetao** [comment]
Crio um arquivo xml mínimo para todos os projeto de um professor, ou só para cada projeto individualmente, não organizando por professor? 
E os métodos de teste, vão integrando o models tbm?

**Comment by magsilva** [comment]
Quant ao XML, Coloque apenas um professor e um projeto dele. No caso de projetos que possuem ligação com outro professor do DACOM, coloque também o respectivo professor (sem informar projeto).

Em relação ao metodo de teste, sim, pode integrar o model:
1. Fazer o parsing e salvar as coisas no modelo.
2. Recuperar o projeto no modelo.
3. Comparar os dados do projeto recuperado do modelo com os dados esperados.

Observe também que será necessário configurar outra base de dados (para os teste você pode usar uma base sqlite3). No setUp() ele deve criar a base, ok?
