### ISSUE TITLE
Organizar as pessoas de acordo com a função

### ISSUE THREAD

**Issue by magsilva** [humbbetao/projectUtfpr#13]
Atualmente as pessoas do departamento são mostradas de forma agrupada. Podemos organizar a página de pessoas de acordo com as seguintes categorias:
- Docentes
- Técnicos administrativos
- Estagiários

**Comment by humbbetao** [comment]
Deve ter uma separação, mostrando primeiro os docentes, depois os técnicos e posteriormente os estagiários, correto? E marcando com uma tag quem é quem.

**Comment by magsilva** [comment]
Sim. Teremos de acrescentar  "Estagiário" no modelo: Nome, Função, Data inicial, Data final (para mostrar, basta nome e função: vai mostrar de acordo com a data final).
