### ISSUE TITLE
Incluir informações sobre infraestrutura

### ISSUE THREAD

**Issue by magsilva** [humbbetao/projectUtfpr#14]
O site deveria apresentar informações sobre infraestrutura. Não se preocupe em colocar no menu principal, depois pensamos como acessar facilmente esta informação. A página em si deve apresentar os seguintes dados:
- Sala da chefia de departamento (local, telefone)
- Salas de professores (locais, telefones)
- Secretaria (local, telefone)
- Laboratórios (quais)
- Salas de aula teórica (quantidade)

**Comment by humbbetao** [comment]
Todo sala/laboratório tem um técnico responsável
