### ISSUE TITLE
Permitir a publicação de eventos

### ISSUE THREAD

**Issue by magsilva** [humbbetao/projectUtfpr#15]
Eventos realizados pelo DACOM e cursos devem ser divulgados pelo site. Tipos de eventos que devem ser contemplados:
- Palestra
- Cursos de curta duração
- Semana acadêmica
- Banca de defesa de TCC
- Simpósio de estágios

**Comment by humbbetao** [comment]
Esses eventos devem ser mostrado na página inicial certo?

**Comment by magsilva** [comment]
Sim.
