### ISSUE TITLE
Incluir informações sobre o Centro Acadêmico

### ISSUE THREAD

**Issue by magsilva** [humbbetao/projectUtfpr#17]
Incluir informações sobre o Centro Acadêmico e link para o site deste.

**Comment by humbbetao** [comment]
Tanto a Empresa Júnior e Centro Acadêmico, pode se colocar numa mesma página com nome de "Afiliados" do departamento ou da coordenação?

**Comment by magsilva** [comment]
A Empresa Junior esta atrelada ao departamento e o Centro Acadêmico está relacionado com o curso. Por enquanto coloque as informações no modelo e, talvez, no final das informações sobre o curso. Depois vemos onde colocar em definitivo.
