### ISSUE TITLE
Incluir informações sobre Colegiado e NDE de cada curso

### ISSUE THREAD

**Issue by magsilva** [humbbetao/projectUtfpr#18]
Os cursos de graduação possuem um colegiado e um NDE. Ambos devem constar na página do curso (após a informação sobre o coordenador).

**Comment by humbbetao** [comment]
Colegiado é composto por professores, estagiários e ténicos administrativos ?

**Comment by magsilva** [comment]
Quase! A constituição é a seguinte:
- coordenador de curso
- professor do DACOM responsável pela atividade de estágio;
- professor do DACOM responsável pelo trabalho de conclusão de curso;
- professor do DACOM responsável pelas atividades complementares;
- professores eleitos. Para cada professor eleito, existe um suplente.
- ao menos um aluno

A composição do NDE é a seguinte:
- coordenador de curso
- professores
