### ISSUE TITLE
Incluir informações sobre regulamentação e autorização do curso

### ISSUE THREAD

**Issue by magsilva** [humbbetao/projectUtfpr#19]
Na página do curso, devem ser incluídas informações de carater legal:
- Projeto Político Pedagógico Institucional: http://www.utfpr.edu.br/a-instituicao/documentos-institucionais/projeto-politico-pedagogico-institucional-1
- Plano de Desenvolvimento Institucional: http://www.utfpr.edu.br/a-instituicao/documentos-institucionais/pdi-2013-2017
- Regulamentos
- Projeto Pedagógico

**Comment by humbbetao** [comment]
Essas informações ficam casdatradas em curso ou matriz?

**Comment by magsilva** [comment]
O PPP, PDI (dois primeiros) e regulamentos são informações globais válidas para qualquer curso. O projeto pedagógico fica atrelado à matriz.
