### ISSUE TITLE
Mostrar horários e locais de disciplina

### ISSUE THREAD

**Issue by magsilva** [humbbetao/projectUtfpr#20]
Registrar o oferecimento de uma disciplina, informando os horários e locais de aula.

**Comment by humbbetao** [comment]
Isso deve ser mostrado em versão ampliada das disciplinas separadamente, já que fica muita informação colocar na página de curso, que mostra a ementa?

**Comment by magsilva** [comment]
Por enquanto, apenas algo mais simples. Na disciplina, podemos colocar uma tabela informando cada oferecimento: sigla da turma, professores, dias da semana e respectivos horários.
