### ISSUE TITLE
Armazenar o Calendário Acadêmico

### ISSUE THREAD

**Issue by magsilva** [humbbetao/projectUtfpr#21]
Armazenar o Calendário Acadêmico (informação da UTFPR). Depois associaremos essas informações com os eventos registrados no sistema.

**Comment by humbbetao** [comment]
Armazeno aquele pdf do ano e as informações dele no models tbm?

**Comment by magsilva** [comment]
Não precisamos do PDF, apenas as informações dele mesmo.
