### ISSUE TITLE
Acrescentar informações de regulamentação aos cursos

### ISSUE THREAD

**Issue by magsilva** [humbbetao/projectUtfpr#8]
Para cada curso, existem três tipos de "disciplinas" especiais: TCC, Atividades complementares e Estágio. Para estas disciplinas ou curso, é necessário vincular regulamentação específica. Precisamos incluir esta informação (provavelmente vinculadas ao curso).

**Comment by humbbetao** [comment]
Estou com duvida, para isso criarei um campo de tcc, atividades complementares e estagio no curso?

**Comment by magsilva** [comment]
Podem ser três campos livres, que permitam a inserção desta informação textualmente.
