### ISSUE TITLE
Adicionar 'Plano de ensino' ao modelo

### ISSUE THREAD

**Issue by magsilva** [humbbetao/projectUtfpr#9]
Adicionar 'Plano de ensino' ao modelo e permitir a vinculação de planos a uma disciplina (um plano por disciplina-turma).

**Comment by humbbetao** [comment]
Plano de ensino vai ser uma nova classe no modelo?

**Comment by magsilva** [comment]
Sim, coloque como uma classe. Por enquanto, ela conterá um atributo que será um arquivo.

**Comment by magsilva** [comment]
Aproveitando, façamos um pouco diferente. Ao invés de chamar "Plano de ensino", chame de "Plano de aula". As informações típicas do "Plano de ensino" já constam em Disciplina.
